services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/.env:/var/www/.env
    env_file:
      - ./Backend/.env
    stdin_open: true
    tty: true
